[package]
name = "playground"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.7.2"
lazy_static = "1.4.0"
smart_led_effects = { path = "../smart_led_effects" }
